"""
Blitz Executor — fast-path order execution for last-second opportunities.

PURPOSE:
    Picks up BLITZ_READY signals generated by BlitzScanner and converts them
    into positions as fast as possible using market orders. This executor
    operates on a separate capital pool (20% of SGE) with its own risk limits.

WHY A SEPARATE EXECUTOR:
    The standard OrderExecutor runs on a 3-second cycle with patient limit
    orders and full policy gate checks. The Blitz Executor:
    - Runs on a 1-second cycle (matches BlitzScanner)
    - Uses market orders for instant fill
    - Applies Blitz-specific risk policy (higher Kelly, wider stops)
    - Bypasses the standard signal routing pipeline
    - Has its own circuit breaker and position limits

EXECUTION FLOW:
    1. Fetch oldest BLITZ_READY signal from signals table.
    2. Verify Blitz engine state: available capital, circuit breaker, position count.
    3. Position sizing: Blitz Kelly fraction × Blitz available capital.
    4. Category concentration check: max 40% of Blitz pool in one category.
    5. Order placement (market order for speed).
    6. Record: write to positions + executions with engine='SGE_BLITZ'.
    7. Update signal status → EXECUTED.

CAPITAL ISOLATION:
    Blitz positions are tagged with engine='SGE_BLITZ' in the positions table.
    This ensures they don't count against standard SGE limits and vice versa.
    The EngineStateManager tracks SGE_BLITZ as a sub-engine of SGE.

POLLING: Every 1 second.
"""

from __future__ import annotations

import logging
import time
from typing import Any

from sibyl.core.base_agent import BaseAgent
from sibyl.core.database import DatabaseManager

logger = logging.getLogger("sibyl.agents.sge.blitz_executor")


class BlitzExecutor(BaseAgent):
    """Fast-path executor for Blitz partition signals.

    Converts BLITZ_READY signals into positions using market orders.
    Operates on the SGE_BLITZ sub-engine capital pool.
    """

    def __init__(
        self,
        db: DatabaseManager,
        config: dict[str, Any],
        mode: str = "paper",
    ) -> None:
        super().__init__(name="blitz_executor", db=db, config=config, engine="SGE")
        self._mode = mode
        self._enabled = False

        # Blitz risk policy (loaded from config)
        self._kelly_fraction = 0.25
        self._max_single_position_pct = 0.08
        self._max_concurrent_positions = 5
        self._per_trade_stop_loss_pct = 0.50
        self._circuit_breaker_drawdown_pct = 0.15
        self._daily_loss_limit_pct = 0.08
        self._max_category_concentration = 0.40
        self._max_slippage_cents = 3

        # Kalshi client for live orders
        self._kalshi_client = None

        # Policy engine for avoidance rule enforcement (Sprint 14 Section 20)
        self._policy = None

        # Stats
        self._executions = 0
        self._rejections = 0

    @property
    def poll_interval(self) -> float:
        """Run every 1 second — match BlitzScanner frequency."""
        return 1.0

    async def start(self) -> None:
        """Load Blitz config and initialize Kalshi client."""
        import os
        from sibyl.core.config import load_yaml

        try:
            sge = load_yaml("sge_config.yaml")
            blitz = sge.get("blitz", {})
        except FileNotFoundError:
            self.logger.warning("sge_config.yaml not found — Blitz disabled")
            return

        self._enabled = blitz.get("enabled", False)
        if not self._enabled:
            self.logger.info("Blitz Executor disabled")
            return

        # Load risk policy
        risk = blitz.get("risk_policy", {})
        self._kelly_fraction = float(risk.get("kelly_fraction", 0.25))
        self._max_single_position_pct = float(risk.get("max_single_position_pct", 0.08))
        self._max_concurrent_positions = int(risk.get("max_concurrent_positions", 5))
        self._per_trade_stop_loss_pct = float(risk.get("per_trade_stop_loss_pct", 0.50))
        self._circuit_breaker_drawdown_pct = float(risk.get("circuit_breaker_drawdown_pct", 0.15))
        self._daily_loss_limit_pct = float(risk.get("daily_loss_limit_pct", 0.08))
        self._max_category_concentration = float(risk.get("max_category_concentration", 0.40))

        execution = blitz.get("execution", {})
        self._max_slippage_cents = int(execution.get("max_slippage_cents", 3))

        # Ensure SGE_BLITZ engine state row exists
        existing = await self.db.fetchone(
            "SELECT engine FROM engine_state WHERE engine = 'SGE_BLITZ'"
        )
        if not existing:
            await self.db.execute(
                "INSERT INTO engine_state (engine, circuit_breaker) VALUES ('SGE_BLITZ', 'CLEAR')"
            )
            await self.db.commit()

        # Initialize Policy Engine for avoidance rule checks (Section 20)
        from sibyl.core.policy import PolicyEngine
        self._policy = PolicyEngine()
        try:
            self._policy.initialize()
            self.logger.info("PolicyEngine loaded for Blitz avoidance checks")
        except FileNotFoundError:
            self.logger.warning("Policy config not found — avoidance checks disabled")
            self._policy = None

        # Initialize Kalshi client for live mode
        if self._mode == "live":
            from sibyl.clients.kalshi_client import KalshiClient
            key_id = os.environ.get("KALSHI_KEY_ID")
            key_path = os.environ.get("KALSHI_PRIVATE_KEY_PATH")
            if key_id and key_path:
                rate_limit = float(
                    self.config.get("platforms", {}).get("kalshi", {}).get(
                        "rate_limit_per_second", 8
                    )
                )
                self._kalshi_client = KalshiClient(
                    key_id=key_id,
                    private_key_path=key_path,
                    rate_limit=rate_limit,
                )

        self.logger.info(
            "Blitz Executor started (mode=%s, kelly=%.2f, max_pos=%d)",
            self._mode, self._kelly_fraction, self._max_concurrent_positions,
        )

    async def run_cycle(self) -> None:
        """Process one BLITZ_READY signal per cycle."""
        if not self._enabled:
            return

        # ── Fetch oldest BLITZ_READY signal ───────────────────────────
        signal = await self.db.fetchone(
            """SELECT s.id, s.market_id, s.signal_type, s.confidence,
                      s.ev_estimate, s.detection_modes_triggered, s.reasoning,
                      m.category
               FROM signals s
               LEFT JOIN markets m ON s.market_id = m.id
               WHERE s.status = 'BLITZ_READY'
               ORDER BY s.timestamp ASC
               LIMIT 1"""
        )
        if not signal:
            return

        # ── Parse direction from detection_modes_triggered field ──────
        modes = signal["detection_modes_triggered"] or ""
        direction = "YES"
        if "DIR:NO" in modes:
            direction = "NO"
        elif "DIR:YES" in modes:
            direction = "YES"

        market_id = signal["market_id"]
        confidence = float(signal["confidence"])
        ev = float(signal["ev_estimate"] or 0)
        category = signal["category"] or "Unknown"

        # ── Policy gate: universal avoidance rules (Section 20) ───────
        # Blitz is exempt from most policy rules, but universal avoidance
        # (min liquidity, subjective resolution) still applies.
        if self._policy and self._policy.initialized:
            market_data = {"category": category, "market_id": market_id,
                           "open_interest": 99999}
            signal_data_for_policy = {"confidence": confidence, "ev": ev}
            decision = self._policy.pre_trade_gate(
                signal_data=signal_data_for_policy,
                market_data=market_data,
                engine="SGE_BLITZ",
            )
            if not decision.approved:
                await self._reject_signal(signal["id"], f"POLICY:{decision.rejection_reason}")
                return

        # ── Risk gate: circuit breaker ────────────────────────────────
        state = await self.db.fetchone(
            "SELECT * FROM engine_state WHERE engine = 'SGE_BLITZ'"
        )
        if not state:
            self.logger.warning("No SGE_BLITZ engine state — skipping")
            await self._reject_signal(signal["id"], "NO_ENGINE_STATE")
            return

        if state["circuit_breaker"] == "TRIGGERED":
            self.logger.warning("Blitz circuit breaker TRIGGERED — skipping")
            await self._reject_signal(signal["id"], "CIRCUIT_BREAKER")
            return

        available = float(state["available_capital"])
        if available <= 0:
            await self._reject_signal(signal["id"], "NO_CAPITAL")
            return

        # ── Risk gate: concurrent position limit ──────────────────────
        open_count_row = await self.db.fetchone(
            """SELECT COUNT(*) as cnt FROM positions
               WHERE engine = 'SGE_BLITZ' AND status = 'OPEN'"""
        )
        open_count = open_count_row["cnt"] if open_count_row else 0
        if open_count >= self._max_concurrent_positions:
            await self._reject_signal(signal["id"], "MAX_POSITIONS")
            return

        # ── Risk gate: category concentration ─────────────────────────
        total_blitz = float(state["total_capital"]) if state else 0
        if total_blitz > 0:
            cat_deployed = await self.db.fetchone(
                """SELECT COALESCE(SUM(p.size * p.entry_price), 0) as deployed
                   FROM positions p
                   JOIN markets m ON p.market_id = m.id
                   WHERE p.engine = 'SGE_BLITZ' AND p.status = 'OPEN'
                     AND m.category = ?""",
                (category,),
            )
            cat_exposure = float(cat_deployed["deployed"]) / total_blitz if cat_deployed else 0
            if cat_exposure >= self._max_category_concentration:
                await self._reject_signal(signal["id"], f"CAT_CONCENTRATION:{category}")
                return

        # ── Get current price ─────────────────────────────────────────
        price_row = await self.db.fetchone(
            """SELECT yes_price FROM prices
               WHERE market_id = ? ORDER BY timestamp DESC LIMIT 1""",
            (market_id,),
        )
        if not price_row:
            await self._reject_signal(signal["id"], "NO_PRICE")
            return

        yes_price = float(price_row["yes_price"])
        entry_price = yes_price if direction == "YES" else (1.0 - yes_price)

        if entry_price <= 0 or entry_price >= 1.0:
            await self._reject_signal(signal["id"], "INVALID_PRICE")
            return

        # ── Position sizing (Blitz Kelly) ─────────────────────────────
        payout = (1.0 / entry_price) - 1.0
        if payout <= 0:
            await self._reject_signal(signal["id"], "NO_PAYOUT")
            return

        kelly_raw = (confidence * payout - (1.0 - confidence)) / payout
        kelly_raw = max(kelly_raw, 0)
        kelly_capped = min(kelly_raw, self._kelly_fraction)

        position_dollars = min(kelly_capped, self._max_single_position_pct) * available
        if position_dollars < 1.0:
            await self._reject_signal(signal["id"], "SIZE_TOO_SMALL")
            return

        size_contracts = int(position_dollars / entry_price)
        if size_contracts < 1:
            await self._reject_signal(signal["id"], "ZERO_CONTRACTS")
            return

        # ── Execute: market order for speed ───────────────────────────
        order_id = f"BLITZ-{int(time.time() * 1000)}"

        if self._mode == "live" and self._kalshi_client:
            price_cents = int(entry_price * 100)
            try:
                result = await self._kalshi_client.place_order(
                    ticker=market_id,
                    side=direction.lower(),
                    size=size_contracts,
                    price_cents=price_cents,
                    order_type="market",
                )
                if result and "order" in result:
                    order_id = result["order"].get("order_id", order_id)
                    # Slippage check
                    fill_price = result["order"].get("avg_fill_price", price_cents)
                    if isinstance(fill_price, (int, float)):
                        slippage = abs(fill_price - price_cents)
                        if slippage > self._max_slippage_cents:
                            self.logger.warning(
                                "BLITZ SLIPPAGE: %d¢ on %s (max=%d¢)",
                                slippage, market_id, self._max_slippage_cents,
                            )
                else:
                    self.logger.error("BLITZ LIVE ORDER FAILED: %s", market_id)
                    await self._reject_signal(signal["id"], "ORDER_FAILED")
                    return
            except Exception:
                self.logger.exception("BLITZ LIVE ORDER EXCEPTION: %s", market_id)
                await self._reject_signal(signal["id"], "ORDER_EXCEPTION")
                return

        # ── Stop loss (wider for Blitz — positions resolve in seconds) ─
        stop_loss = entry_price * (1.0 - self._per_trade_stop_loss_pct)

        # ── Write position (engine = SGE_BLITZ) ──────────────────────
        await self.db.execute(
            """INSERT INTO positions
               (market_id, platform, engine, side, size, entry_price,
                current_price, stop_loss, status, signal_id, thesis)
               VALUES (?, 'kalshi', 'SGE_BLITZ', ?, ?, ?, ?, ?, 'OPEN', ?, ?)""",
            (
                market_id, direction, float(size_contracts), entry_price,
                yes_price, stop_loss, signal["id"],
                f"BLITZ #{signal['id']}: {direction} (conf={confidence:.2f}, ev={ev:.3f})",
            ),
        )

        # ── Write execution record ────────────────────────────────────
        await self.db.execute(
            """INSERT INTO executions
               (signal_id, engine, platform, order_id, side, fill_price, size, order_type)
               VALUES (?, 'SGE_BLITZ', 'kalshi', ?, 'BUY', ?, ?, 'market')""",
            (signal["id"], order_id, entry_price, float(size_contracts)),
        )

        # ── Mark signal as EXECUTED ───────────────────────────────────
        await self.db.execute(
            "UPDATE signals SET status = 'EXECUTED', routed_to = 'SGE_BLITZ' WHERE id = ?",
            (signal["id"],),
        )
        await self.db.commit()

        self._executions += 1
        self.logger.info(
            "BLITZ EXECUTED: %s %s %d contracts @ %.2f (ev=%.3f, conf=%.2f)",
            direction, market_id, size_contracts, entry_price, ev, confidence,
        )

    async def stop(self) -> None:
        """Graceful shutdown."""
        if self._kalshi_client:
            await self._kalshi_client.close()
        self.logger.info(
            "Blitz Executor stopped (executed=%d, rejected=%d)",
            self._executions, self._rejections,
        )

    # ── Helpers ───────────────────────────────────────────────────────────

    async def _reject_signal(self, signal_id: int, reason: str) -> None:
        """Mark a BLITZ signal as rejected with reason."""
        await self.db.execute(
            "UPDATE signals SET status = 'REJECTED', reasoning = reasoning || ' REJECTED:' || ? WHERE id = ?",
            (reason, signal_id),
        )
        await self.db.commit()
        self._rejections += 1
        self.logger.debug("Blitz signal %d rejected: %s", signal_id, reason)

    def health_check(self) -> dict[str, Any]:
        """Return Blitz Executor health status."""
        base = super().health_check()
        base.update({
            "enabled": self._enabled,
            "mode": self._mode,
            "executions": self._executions,
            "rejections": self._rejections,
        })
        return base
