"""
Base Signal Pipeline — shared infrastructure for all category pipelines.

Each category pipeline inherits from BasePipeline and implements:
    - _get_clients(): returns the list of data clients it uses
    - _analyze(): fetches data, compares against Kalshi market state, yields signals

SIGNAL GENERATION LOGIC:
    1. Pipeline queries `markets` table for active markets in its category.
    2. Pipeline fetches fresh data from its data clients.
    3. Pipeline compares real-world data against market prices to detect mispricings.
    4. When edge is detected (data implies price should be higher/lower than market),
       pipeline generates a signal with confidence based on data reliability and
       magnitude of the mispricing.
    5. Signals are written to `signals` table with status=PENDING for the
       SignalRouter to pick up.

SIGNAL TYPES GENERATED:
    DATA_FUNDAMENTAL:  Based on hard data (FRED rates, BLS employment, weather models)
    DATA_SENTIMENT:    Based on sentiment/social data (trending, pageviews, fear/greed)
    DATA_MOMENTUM:     Based on directional trends in data (rising CPI, falling unemployment)
    DATA_DIVERGENCE:   Data disagrees with market price (model says X, market says Y)
    DATA_CATALYST:     Upcoming event likely to move market (earnings, FDA date, game)
"""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from sibyl.core.database import DatabaseManager
    from sibyl.clients.base_data_client import BaseDataClient

logger = logging.getLogger("sibyl.pipelines.base")


# ── Signal Output ────────────────────────────────────────────────────────

@dataclass
class PipelineSignal:
    """A trading signal generated by a category pipeline.

    This is the intermediate format before writing to the database.
    """
    market_id: str
    signal_type: str                  # DATA_FUNDAMENTAL, DATA_DIVERGENCE, etc.
    confidence: float                 # 0.0–1.0
    ev_estimate: float = 0.0           # Expected value (positive = profitable)
    direction: str = "YES"            # "YES" or "NO" — which side to trade
    reasoning: str = ""               # Human-readable explanation
    source_pipeline: str = ""         # Which pipeline generated this
    data_points: dict[str, Any] = field(default_factory=dict)  # Raw data for audit
    category: str = ""                # Market category
    timeframe: str = ""               # Sprint 24: 15min/hourly/4hour/daily/monthly


# ── Base Pipeline ────────────────────────────────────────────────────────

class BasePipeline(ABC):
    """Abstract base class for all category signal pipelines.

    Subclasses implement _analyze() to transform API data into signals.

    Lifecycle:
        pipeline = EconomicsPipeline(db)
        await pipeline.initialize()   # Init data clients
        signals = await pipeline.run()  # Fetch data → generate signals → write to DB
        await pipeline.close()         # Cleanup data clients
    """

    CATEGORY: str = ""              # Override in subclass (e.g., "Economics")
    PIPELINE_NAME: str = ""         # Override in subclass (e.g., "economics")

    # Per-category dedup windows (minutes).  Tuned per Sprint 16.
    # Subclasses can override.  The _write_signals() method uses this value
    # instead of the old hardcoded 60-minute window.
    #
    # Rationale:
    #   - Crypto: 15min  (prices move fast, signals need rapid refresh)
    #   - Sports: 30min  (game state changes quickly during live events)
    #   - Financial: 60min (default, standard market hours)
    #   - Weather: 120min (forecasts update slowly)
    #   - Culture: 120min (event outcomes don't change rapidly)
    #   - Geopolitics: 120min (political events are slow-moving)
    #   - Economics: 240min (data releases are infrequent)
    #   - Science: 360min (FDA/NASA calendars rarely change intra-day)
    DEDUP_WINDOW_MINUTES: int = 60  # Default; subclasses override

    def __init__(self, db: DatabaseManager) -> None:
        self._db = db
        self._clients: list[BaseDataClient] = []
        self._initialized = False
        self.logger = logging.getLogger(f"sibyl.pipelines.{self.PIPELINE_NAME}")

    @property
    def initialized(self) -> bool:
        return self._initialized

    @property
    def clients(self) -> list[BaseDataClient]:
        """Public accessor for data clients (used by subclass _analyze methods)."""
        return self._clients

    @abstractmethod
    def _create_clients(self) -> list[BaseDataClient]:
        """Create and return the data clients used by this pipeline."""
        ...

    @abstractmethod
    async def _analyze(self, markets: list[dict]) -> list[PipelineSignal]:
        """Analyze data and generate signals for active markets in this category.

        Args:
            markets: Active markets from DB matching this pipeline's category.
                     Each dict has keys: id, title, category, close_date, status.

        Returns:
            List of PipelineSignal objects to write to the database.
        """
        ...

    async def initialize(self) -> bool:
        """Initialize all data clients. Returns True if at least one is ready."""
        self._clients = self._create_clients()
        ready_count = 0
        for client in self._clients:
            try:
                if client.initialize():
                    ready_count += 1
            except Exception as e:
                self.logger.warning("Failed to initialize %s: %s", client.name, e)
        self._initialized = ready_count > 0
        self.logger.info(
            "%s pipeline initialized (%d/%d clients ready)",
            self.PIPELINE_NAME, ready_count, len(self._clients),
        )
        return self._initialized

    async def close(self) -> None:
        """Close all data clients."""
        for client in self._clients:
            try:
                await client.close()
            except Exception:
                pass
        self._initialized = False

    async def run(self) -> list[PipelineSignal]:
        """Execute the full pipeline: fetch markets → analyze → write signals.

        Returns:
            List of generated PipelineSignal objects.
        """
        if not self._initialized:
            self.logger.warning("%s pipeline not initialized", self.PIPELINE_NAME)
            return []

        # Step 1: Get active markets for this category
        markets = await self._get_category_markets()
        if not markets:
            self.logger.debug("No active %s markets found", self.CATEGORY)
            # Still run analysis — pipelines can generate signals for
            # markets that match by keyword even if category isn't set
            markets = []

        # Step 2: Run pipeline-specific analysis
        # Handle both sync and async _analyze() implementations.
        # Some subclasses define _analyze as sync (returns list directly),
        # others as async (returns coroutine). We handle both.
        try:
            result = self._analyze(markets)
            import asyncio
            if asyncio.iscoroutine(result):
                signals = await result
            else:
                signals = result
        except Exception as e:
            self.logger.error("%s pipeline analysis failed: %s", self.PIPELINE_NAME, e)
            return []

        # Step 3: Filter and validate signals
        valid_signals = self._validate_signals(signals)

        # Step 4: Write signals to database
        written = await self._write_signals(valid_signals)

        self.logger.info(
            "%s pipeline: %d signals generated, %d written to DB",
            self.PIPELINE_NAME, len(valid_signals), written,
        )
        return valid_signals

    # Maximum look-ahead window for market analysis.  Markets closing
    # further out than this aren't actionable and waste pipeline budget.
    MARKET_HORIZON_DAYS: int = 14

    async def _get_category_markets(self) -> list[dict]:
        """Fetch active Kalshi markets matching this pipeline's category.

        Sprint 19 fixes:
          1. Filter to Kalshi-only (Polymarket can't be executed).
          2. Limit to markets closing within MARKET_HORIZON_DAYS.
             Far-future markets have no actionable price data and
             bloat pipeline runtimes (29K+ markets → timeouts).
        """
        # Match on exact category or similar names
        category_variants = self._category_variants()
        placeholders = ",".join("?" for _ in category_variants)

        rows = await self._db.fetchall(
            f"""SELECT id, title, category, close_date, status, platform
                FROM markets
                WHERE status = 'active'
                  AND platform = 'kalshi'
                  AND close_date <= datetime('now', '+{self.MARKET_HORIZON_DAYS} days')
                  AND category IN ({placeholders})
                ORDER BY close_date ASC""",
            tuple(category_variants),
        )
        return [dict(row) for row in rows]

    def _category_variants(self) -> list[str]:
        """Return category name variants for DB matching.

        Override in subclasses that span multiple Kalshi categories.
        """
        variants = [self.CATEGORY]
        # Add lowercase variant
        if self.CATEGORY.lower() != self.CATEGORY:
            variants.append(self.CATEGORY.lower())
        return variants

    def _validate_signals(self, signals: list[PipelineSignal]) -> list[PipelineSignal]:
        """Filter out invalid or low-quality signals."""
        # Sprint 24: Load calibration offset for this category.
        # Research: domain-specific biases (politics +0.15 underconfident,
        # weather/culture -0.09 overconfident, economics 0.00).
        calibration_offset = 0.0
        try:
            from sibyl.core.config import load_yaml
            policy = load_yaml("investment_policy_config.yaml")
            profiles = policy.get("per_category_risk_profiles", {})
            cat_key = self.CATEGORY.lower() if self.CATEGORY else ""
            profile = profiles.get(cat_key, profiles.get(self.CATEGORY, {}))
            calibration_offset = float(profile.get("calibration_offset", 0.0))
        except Exception:
            pass

        valid = []
        for sig in signals:
            # Apply domain calibration offset
            if calibration_offset != 0.0:
                sig.confidence += calibration_offset

            # Enforce confidence bounds
            sig.confidence = max(0.0, min(sig.confidence, 0.99))

            # Minimum confidence threshold
            if sig.confidence < 0.50:
                continue

            # Must have a market_id
            if not sig.market_id:
                continue

            # Set source pipeline
            sig.source_pipeline = self.PIPELINE_NAME
            sig.category = self.CATEGORY

            valid.append(sig)
        return valid

    async def _write_signals(self, signals: list[PipelineSignal]) -> int:
        """Write validated signals to the signals table.

        Sprint 24: Batch dedup — pre-fetch open positions and recent signals
        in two queries instead of 2 × N individual lookups.  Reduces DB
        round-trips from ~9000 to ~N+2 for a typical 3000-signal batch.
        """
        if not signals:
            return 0

        # ── Batch dedup: pre-fetch open position market_ids ──────────
        open_rows = await self._db.fetchall(
            "SELECT DISTINCT market_id FROM positions WHERE status = 'OPEN'"
        )
        open_market_ids: set[str] = {row["market_id"] for row in open_rows}

        # ── Batch dedup: pre-fetch recent signals within dedup window ─
        dedup_minutes = self.DEDUP_WINDOW_MINUTES
        recent_rows = await self._db.fetchall(
            """SELECT market_id, signal_type FROM signals
               WHERE source_pipeline = ?
                 AND timestamp >= datetime('now', ? || ' minutes')""",
            (self.PIPELINE_NAME, f"-{dedup_minutes}"),
        )
        recent_keys: set[tuple[str, str]] = {
            (row["market_id"], row["signal_type"]) for row in recent_rows
        }

        # ── Filter and batch insert ──────────────────────────────────
        written = 0
        skipped_open = 0
        skipped_dedup = 0
        for sig in signals:
            try:
                if sig.market_id in open_market_ids:
                    skipped_open += 1
                    continue

                if (sig.market_id, sig.signal_type) in recent_keys:
                    skipped_dedup += 1
                    continue

                await self._db.execute(
                    """INSERT INTO signals
                       (market_id, signal_type, confidence, ev_estimate,
                        status, detection_modes_triggered, reasoning,
                        direction, source_pipeline, timeframe)
                       VALUES (?, ?, ?, ?, 'PENDING', ?, ?, ?, ?, ?)""",
                    (
                        sig.market_id,
                        sig.signal_type,
                        round(sig.confidence, 4),
                        round(sig.ev_estimate, 4),
                        f"PIPELINE:{self.PIPELINE_NAME}|DIR:{sig.direction}",
                        sig.reasoning,
                        sig.direction,
                        self.PIPELINE_NAME,
                        sig.timeframe or None,
                    ),
                )
                # Track for intra-batch dedup
                recent_keys.add((sig.market_id, sig.signal_type))
                written += 1
            except Exception as e:
                self.logger.error(
                    "Failed to write signal for %s: %s", sig.market_id, e
                )
        if written:
            await self._db.commit()
        if skipped_open or skipped_dedup:
            self.logger.info(
                "Signal dedup: %d open-position, %d recent-signal skipped",
                skipped_open, skipped_dedup,
            )
        return written

    # ── Utility Methods ──────────────────────────────────────────────

    def _get_client(self, name: str) -> BaseDataClient | None:
        """Get a specific client by name."""
        for client in self._clients:
            if client.name.lower() == name.lower():
                return client
        return None

    @staticmethod
    def _compute_edge(
        data_implied_probability: float,
        market_price: float,
        half_spread: float = 0.0,
        fee_per_contract: float = 0.014,
        fee_multiplier: float = 2.0,
    ) -> tuple[float, str, float]:
        """Compute trading edge between data-implied probability and market price.

        Sprint 22: Added half_spread parameter to account for execution costs.
        Sprint 26: Added fee_per_contract to deduct Kalshi roundtrip fees from EV.
        Sprint 27: Added fee_multiplier (default 2.0x) — edge must exceed 2x the
        fee to be considered positive EV. Provides a safety margin above raw cost.

        Args:
            data_implied_probability: What the data says the probability should be (0-1).
            market_price:             Current market YES price (0-1).
            half_spread:              Half the bid-ask spread (0-1).
            fee_per_contract:         Estimated roundtrip fee as fraction of $1 contract.
                                      Default 0.014 (1.4%) for Kalshi taker fills.
            fee_multiplier:           Multiplier on fee for safety margin.
                                      Default 2.0 (edge must exceed 2.8% to trade).

        Returns:
            (edge_magnitude, direction, ev_estimate)
            - edge_magnitude: absolute size of the edge (0-1)
            - direction: "YES" if data says underpriced, "NO" if overpriced
            - ev_estimate: expected value of the trade, net of spread + fees
        """
        edge = data_implied_probability - market_price
        fee_cost = fee_per_contract * fee_multiplier

        if edge > 0:
            direction = "YES"
            ev = data_implied_probability - market_price - half_spread - fee_cost
        else:
            direction = "NO"
            ev = (1.0 - data_implied_probability) - (1.0 - market_price) - half_spread - fee_cost

        edge_magnitude = abs(edge)
        return edge_magnitude, direction, ev

    @staticmethod
    def _edge_to_confidence(edge: float, base: float = 0.55, scale: float = 2.0) -> float:
        """Convert edge magnitude to confidence score.

        Args:
            edge:  Absolute edge (0-1).
            base:  Minimum confidence for any signal.
            scale: How much edge amplifies confidence.

        Returns:
            Confidence score (0.0-0.99).
        """
        return min(base + edge * scale, 0.99)
